#include "../include/client_config.h"

#include <fstream>
#include <iostream>
#include <yaml-cpp/yaml.h>

#include "client_global.h"
#include "shared_crypto.h"

namespace config {
  bool check() {
    using namespace YAML;

    try {
      Node config = LoadFile("config.yaml");
    } catch (const BadFile&) {
      return false;
    }
    return true;
  }

  void create_config_file() {
    using namespace YAML;
    using std::ofstream;

    Node config;
    config["uuid"] = shared::crypto::generate_uuid();
    config["name"] = "";
    ofstream file_out("config.yaml");

    add_config_comment(file_out);

    file_out << config;
    file_out.close();
    std::cout << "config file created" << std::endl;

  }

  bool load_config() {
    using namespace YAML;

    Node config = LoadFile("config.yaml");
    global::config::uuid = config["uuid"].as<string>();
    global::config::name = config["name"].as<string>();

    return true;
  }

  void save_new_nickname(const std::string& t_string) {
    using namespace YAML;
    using std::ofstream;

    Node config = LoadFile("config.yaml");
    config["name"] = t_string;
    ofstream file_out("config.yaml");

    add_config_comment(file_out);

    file_out << config;
    file_out.close();
  }

  void add_config_comment(std::ofstream &file_out) {
    using std::ofstream;
    file_out << "# Configuration file\n";
    file_out << "# All server data is saved using UUIDs\n";
    file_out << "# Changing UUID will cause data loss\n";
    file_out << "# DO NOT edit this file manually\n\n";

  }
}