# Client configuration file
# Player identity on servers is based on the UUID stored here
# Changing the username will not change the UUID
# Editing this file manually may cause data loss on servers
# To generate a new UUID, delete this file and restart the client
# WARNING: Doing so will lose access to previous server data

uuid: qn5e7v3w-2bw5iy5x-dq3rpt3i-n2
name: chri_mc_tech
show_fps: false
debug: true
debug_console: false