# Client configuration file
# Player identity on servers is based on the UUID stored here
# Changing the username will not change the UUID
# Editing this file manually may cause data loss on servers
# To generate a new UUID, delete this file and restart the client
# WARNING: Doing so will lose access to previous server data

uuid: w5fbrebm-i6u3p5z6-pnxug243-k2
name: chri_mc_tech
show_fps: true
debug: true